-- ============================================================
-- 03_category_exposure.sql  —  Category Revenue Pareto
-- ============================================================
-- Reads from category_risk_report (built by 05_category_exposure.py)
-- and adds Pareto analysis: which departments account for the
-- first 80% of revenue at risk?
--
-- Business question answered:
--   If I could only address three categories this quarter,
--   which ones represent the majority of the revenue exposure?
--
-- Demonstrates: ROW_NUMBER(), SUM() OVER (ORDER BY ...) for
-- running totals, CASE WHEN for tier classification, ROUND,
-- CROSS JOIN for a scalar denominator without a subquery.
-- ============================================================

WITH

-- -------------------------------------------------------
-- Pull department totals and pre-sort them.
-- department column in category_risk_report is the name.
-- -------------------------------------------------------
dept_base AS (
    SELECT
        department,
        ROUND(dept_total_risk, 0)                           AS revenue_at_risk_60d,
        n_customers                                         AS n_at_risk_customers,
        ROUND(pct_of_total_risk, 1)                         AS pct_of_total,
        -- Add segment breakdown columns if they exist in the report
        -- (Champions and Loyal columns were pivot-generated by Python)
        ROUND(COALESCE("Champions", 0), 0)                  AS champions_risk,
        ROUND(COALESCE("Loyal", 0), 0)                      AS loyal_risk
    FROM category_risk_report
    WHERE dept_total_risk > 0
),

-- -------------------------------------------------------
-- Add risk ranking and running total for Pareto analysis.
-- SUM() OVER (ORDER BY ...) = cumulative sum window function.
-- No GROUP BY needed — the window handles the accumulation.
-- -------------------------------------------------------
ranked AS (
    SELECT
        department,
        revenue_at_risk_60d,
        n_at_risk_customers,
        pct_of_total,
        champions_risk,
        loyal_risk,

        -- Rank by total exposure (1 = most at risk)
        ROW_NUMBER() OVER (ORDER BY revenue_at_risk_60d DESC)      AS risk_rank,

        -- Cumulative risk amount (running total from largest to smallest)
        ROUND(
            SUM(revenue_at_risk_60d) OVER (
                ORDER BY revenue_at_risk_60d DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ), 0
        )                                                           AS cumulative_risk,

        -- Cumulative % of total risk (Pareto curve numerator)
        ROUND(
            SUM(pct_of_total) OVER (
                ORDER BY revenue_at_risk_60d DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ), 1
        )                                                           AS cumulative_pct
    FROM dept_base
),

-- -------------------------------------------------------
-- Classify departments into Pareto tiers.
-- "80/20 rule": which categories account for the first 80%?
-- -------------------------------------------------------
tiered AS (
    SELECT
        *,
        CASE
            WHEN cumulative_pct <= 50  THEN 'Top 50% of risk'
            WHEN cumulative_pct <= 80  THEN 'Next 30% of risk'
            ELSE                            'Tail risk (<20%)'
        END                                                         AS pareto_tier,

        -- Champions vs. Loyal split as a fraction
        CASE
            WHEN (champions_risk + loyal_risk) > 0
            THEN ROUND(champions_risk * 100.0 / (champions_risk + loyal_risk), 1)
            ELSE NULL
        END                                                         AS champions_share_pct
    FROM ranked
)

SELECT
    risk_rank,
    department,
    revenue_at_risk_60d,
    pct_of_total,
    cumulative_pct,
    pareto_tier,
    n_at_risk_customers,
    champions_risk,
    loyal_risk,
    champions_share_pct
FROM tiered
ORDER BY risk_rank
